use education;

INSERT INTO Allcodes (id, keyMap, type, value, createdAt, updatedAt)  values
(1, 'R1', 'ROLE', 'Quản trị viên', current_timestamp, current_timestamp),
(2, 'R2', 'ROLE', 'Giáo viên', current_timestamp, current_timestamp),
(3, 'R3', 'ROLE', 'Học viên', current_timestamp, current_timestamp),
(4, 'S1', 'STATUS', 'Lịch hẹn mới', current_timestamp, current_timestamp),
(5, 'S2', 'STATUS', 'Đã xác nhận', current_timestamp, current_timestamp),
(6, 'S3', 'STATUS', 'Đã dạy xong', current_timestamp, current_timestamp),
(7, 'S4', 'STATUS', 'Đã hủy', current_timestamp, current_timestamp),
(8, 'T1', 'TIME', '8:00 - 9:00', current_timestamp, current_timestamp),
(9, 'T2', 'TIME', '9:00 - 10:00', current_timestamp, current_timestamp),
(10, 'T3', 'TIME', '10:00 - 11:00', current_timestamp, current_timestamp),
(11, 'T4', 'TIME', '11:00 - 12:00', current_timestamp, current_timestamp),
(12, 'T5', 'TIME', '13:00 - 14:00', current_timestamp, current_timestamp),
(13, 'T6', 'TIME', '14:00 - 15:00', current_timestamp, current_timestamp),
(14, 'T7', 'TIME', '15:00 - 16:00', current_timestamp, current_timestamp),
(15, 'T8', 'TIME', '16:00 - 17:00', current_timestamp, current_timestamp),
(16, 'P0', 'POSITION', 'Giáo viên', current_timestamp, current_timestamp),
(17, 'P1', 'POSITION', 'Thạc sĩ', current_timestamp, current_timestamp),
(18, 'P2', 'POSITION', 'Tiến sĩ', current_timestamp, current_timestamp),
(19, 'P3', 'POSITION', 'Phó giáo sư', current_timestamp, current_timestamp),
(20, 'P4', 'POSITION', 'Giáo sư', current_timestamp, current_timestamp),
(21, 'M', 'GENDER', 'Nam', current_timestamp, current_timestamp),
(22, 'F', 'GENDER', 'Nữ', current_timestamp, current_timestamp),
(23, 'O', 'GENDER', 'Khác', current_timestamp, current_timestamp),
(24, 'PRI1', 'PRICE', '200000', current_timestamp, current_timestamp),
(25, 'PRI2', 'PRICE', '250000', current_timestamp, current_timestamp),
(26, 'PRI3', 'PRICE', '300000', current_timestamp, current_timestamp),
(27, 'PRI4', 'PRICE', '350000', current_timestamp, current_timestamp),
(28, 'PRI5', 'PRICE', '400000', current_timestamp, current_timestamp),
(29, 'PRI6', 'PRICE', '450000', current_timestamp, current_timestamp),
(30, 'PRI7', 'PRICE', '500000', current_timestamp, current_timestamp),
(31, 'PAY1', 'PAYMENT', 'Tiền mặt', current_timestamp, current_timestamp),
(32, 'PAY2', 'PAYMENT', 'Thẻ ATM', current_timestamp, current_timestamp),
(33, 'PAY3', 'PAYMENT', 'Tất cả', current_timestamp, current_timestamp),
(34, 'PRO1', 'PROVINCE', 'Hà Nội', current_timestamp, current_timestamp),
(35, 'PRO2', 'PROVINCE', 'Hồ Chí Minh', current_timestamp, current_timestamp),
(36, 'PRO3', 'PROVINCE', 'Đà Nẵng', current_timestamp, current_timestamp),
(37, 'PRO4', 'PROVINCE', 'Cần Thơ', current_timestamp, current_timestamp),
(38, 'PRO5', 'PROVINCE', 'Bình Dương', current_timestamp, current_timestamp),
(39, 'PRO6', 'PROVINCE', 'Đồng Nai', current_timestamp, current_timestamp),
(40, 'PRO7', 'PROVINCE', 'Quảng Ninh', current_timestamp, current_timestamp),
(41, 'PRO8', 'PROVINCE', 'Thừa Thiên Huế', current_timestamp, current_timestamp),
(42, 'PRO9', 'PROVINCE', 'Quảng Bình', current_timestamp, current_timestamp),
(43, 'PRO10', 'PROVINCE', 'Khánh Hòa', current_timestamp, current_timestamp);

INSERT INTO Users (id, email, password, firstName, lastName, address, phoneNumber, gender, image, roleId, positionId, createdAt, updatedAt) VALUES
(1, 'admin@gmail.com', '$2a$10$c2urTqmR3xPTHfxVOruKtu3tYQStONseu2Yo5F7GsALggrOwHHUaG', 'Admin', 'System', 'Mê Linh, Hà Nội', '0123456789', 'M', '', 'R1', 'P0', current_timestamp, current_timestamp),
(2, 'huydang2132@gmail.com', '$2a$10$hM0UDV9DiZnkN7lhPFgahet8wrFD6Vo3oMajDW/WIdPvgocw4J82O', 'Đình Huy', 'Đặng', 'Mê Linh, Hà Nội', '0369555134', 'M', '', 'R1', 'P0', current_timestamp, current_timestamp),
(3, 'teacher@gmail.com', '$2a$10$mThbtFKjW25MatD0W1vLv.nHCi8i4MGPMGHDD9UVputpfL7bk6eZ2', 'Teacher', 'System', 'Hà Nội', '02346345', 'F','', 'R2', 'P1', current_timestamp, current_timestamp),
(4, 'huyluckj@gmail.com', '$2a$10$P975/By2D.YRGd75.ZDiSuSaK6xqpPc487.a4XgBXEt03Ip3c6h3i', 'Hải Anh', 'Nguyễn', 'Mê Linh, Hà Nội', '0234762451', 'F', '', 'R2', 'P0', current_timestamp, current_timestamp),
(5, 'user@gmail.com', '$2a$10$P975/By2D.YRGd75.ZDiSuyqQD7WMWVYE4ETWIDAxLO0N8OKcXthC', 'User', 'Test', 'Test', '0258234908', 'M', '', 'R3', '', current_timestamp, current_timestamp),
(7, 'nhat@gmail.com', '$2a$10$GSnZ6uZ6t/MSTz8xzQ4si.r1L7I9la1Oq2e688CW13bsvvvPpkG32', 'Nhất', 'Phạm', 'Bắc Giang', '235345', 'M', '', 'R2', 'P0', current_timestamp, current_timestamp),
(8, 'phong123hong@gmail.com', '$2a$10$RqarRFiv9N04tzSPhtj4TuNWs3nXl1OhztTmJ5rFH0phPZkNmSSFG', 'Phong', 'Nguyễn Hồng', 'Hà Nội', '0327433067', 'M', '', 'R1', 'P0', current_timestamp, current_timestamp),
(9, 'minh123@gmail.com', '$2a$10$8kqYOWP5RWbpxEBdyi/0Ae6G4ZEGZKa1DSRlziKcxJIaTJJQXy/L.', 'Văn Minh', 'Trương', 'Bắc Giang', '123345', 'M', '', 'R2', 'P0', current_timestamp, current_timestamp),
(10, 'nguyenlan1@gmail.com', '$2a$10$X6SkJjc6ghOIssZBoMQNMewm1TqA8Xct57r8tKx8y1zVzBrbGjpXu', 'Thị Lan', 'Nguyễn', 'Sóc Sơn', '123', 'F', '', 'R2', 'P1', current_timestamp, current_timestamp),
(11, 'nguyenkhuyen1@gmail.com', '$2a$10$X6SkJjc6ghOIssZBoMQNMewm1TqA8Xct57r8tKx8y1zVzBrbGjpXu', 'Thị Khuyến', 'Nguyễn', 'Thường Tín', '123', 'F', '', 'R2', 'P0', current_timestamp, current_timestamp),
(12, 'lekhanh1@gmail.com', '$2a$10$X6SkJjc6ghOIssZBoMQNMewm1TqA8Xct57r8tKx8y1zVzBrbGjpXu', 'Ngọc Khánh', 'Lê', 'Mê Linh', '123', 'M', '', 'R2', 'P3', current_timestamp, current_timestamp),
(13, 'tanhung1@gmail.com', '$2a$10$X6SkJjc6ghOIssZBoMQNMewm1TqA8Xct57r8tKx8y1zVzBrbGjpXu', 'Tấn Hùng', 'Đinh', '123', '123', 'M', '', 'R2', 'P1', current_timestamp, current_timestamp),
(14, 'thuhien@gmail.com', '$2a$10$X6SkJjc6ghOIssZBoMQNMewm1TqA8Xct57r8tKx8y1zVzBrbGjpXu', 'Thị Thu Hiền', 'Đàm', 'Bắc Ninh', '123', 'F', '', 'R2', 'P0', current_timestamp, current_timestamp),
(15, 'ngokien@gmail.com', '$2a$10$X6SkJjc6ghOIssZBoMQNMewm1TqA8Xct57r8tKx8y1zVzBrbGjpXu', 'Sỹ Kiên', 'Ngô', '123', '123', 'M', '', 'R2', 'P4', current_timestamp, current_timestamp);

INSERT INTO teacher_info (id, teacherId, priceId, description, paymentId, centerId, note, rate, createdAt, updatedAt) VALUES
(2, 7, 'PRI3', 'Thầy giáo đến từ Bắc Giang', 'PAY3', 1, 'ielts 7.0', 0, current_timestamp, current_timestamp),
(3, 15, 'PRI3', 'Giáo viên tâm huyết với nghề. Những bài giảng sắc bén, truyền đạt kiến thức một cách tốt nhất.', 'PAY3', 3, 'Giáo viên tâm huyết với nghề.', 0, current_timestamp, current_timestamp),
(4, 11, 'PRI2', 'Giáo viên với niềm đam mê Văn học. Những bài giảng của cô giúp cho học viên cảm thấy yêu môn văn hơn.', 'PAY3', 5, 'Cô Khuyến vui tính', 0, current_timestamp, current_timestamp),
(5, 3, 'PRI2', 'Giáo viên thử nghiệm', 'PAY1', 5, 'Giáo viên thử nghiệm', 0, current_timestamp, current_timestamp),
(1, 4, 'PRI4', 'Sinh viên ưu tú trường Đại học Thương Mại. Sinh viên ngành ngôn ngữ Anh', 'PAY3', 1, 'Cô giáo cute lắm!', 0, current_timestamp, current_timestamp),
(6, 10, 'PRI1', 'Cô giáo đến từ Sóc Sơn :>', 'PAY2', 7, 'Cô này không biết gì đâu :>', 0, current_timestamp, current_timestamp),
(7, 12, 'PRI5', 'Thầy Khánh dạy toán. Toán 10, 11, 12', 'PAY3', 3, 'Thầy dạy toán đỉnh lắm nha', 0, current_timestamp, current_timestamp),
(8, 14, 'PRI4', 'Giáo viên tiếng Anh tốt nghiệp trường Đại học Sư phạm Hà Nội', 'PAY3', 10, 'Cô giáo dạy tâm huyết lắm nha', 0, current_timestamp, current_timestamp),
(9, 13, 'PRI4', '123', 'PAY3', 4, '123', 0, current_timestamp, current_timestamp);

INSERT INTO courses (id, name, listId, teacherId, createdAt, updatedAt) VALUES
(1, 'React Hooks', 'PLqQ6Lvascx2vr-MlKYQCIX2AnfuZ3s0mB', 3, current_timestamp, current_timestamp),
(2, 'Khóa học NodeJs trọn bộ', 'PLqnlyu33Xy-6g7IqU5-3BXOfewcJKoL08', 2, current_timestamp, current_timestamp),
(3, '30 ngày phá đáo 1500 từ vựng chuyên ngành học thuật cùng IELTS Fighter', 'PLSMUNCcswpNXTWoxCVhhiZxr7cv9V9eMW', 4, current_timestamp, current_timestamp),
(4, 'Khóa Học Lập Trình React.js - Redux', 'PLJ5qtRQovuEOoKffoCBzTfvzMTTORnoyp', 2, current_timestamp, current_timestamp),
(5, '[SQL Server] Khóa học sử dụng SQL server', 'PL33lvabfss1xnFpWQF6YH11kMTS1HmLsw', 2, current_timestamp, current_timestamp),
(6, 'Khóa học lập trình Java cơ bản đến hướng đối tượng', 'PL33lvabfss1yGrOutFR03OZoqm91TSsvs', 2, current_timestamp, current_timestamp),
(7, 'Khóa học lập trình C từ cơ bản đến nâng cao', 'PLE1qPKuGSJaCqzcKI9Mr1vByZZOXH_0Uv', 2, current_timestamp, current_timestamp),
(8, 'Khóa học ôn thi THPTQG môn Toán', 'PLDHr_ecbSve4UqI8YN9V3NxMufmwVOuik', 2, current_timestamp, current_timestamp),
(11, 'NGỮ PHÁP TIẾNG HÀN TỔNG HỢP TRUNG CẤP 3 (Full)', 'PL2A1OEE5sYWr9UiUWMewo4UUgOc9nu6_o', 13, current_timestamp, current_timestamp),
(12, 'Khóa tập học machine learning cơ bản', 'PLZEIt444jqpBPoqtW2ARJp9ICnF3c7vJC', 15, current_timestamp, current_timestamp),
(13, 'Toán học lớp 11', 'PL-0677wnvZX9Z_9Tyu_gMapqXjTPOrTLt', 15, current_timestamp, current_timestamp),
(14, 'PHÁT TỤT CÚ ĐỐ ƠN Chúc 9 điểm - Tránh Sai Ngữ Toán', 'PLXmeri-X8nVyKcAPd_FiqAYFyMMlcTB_6', 15, current_timestamp, current_timestamp),
(15, 'Văn Mẫu 9', 'PLpKVg0d65BrLEJP26pyiKqTDdRWTxCh3g', 11, current_timestamp, current_timestamp),
(16, 'PHÁT TỤT CÚ AUDIO TÁC PHẨM VĂN HỌC', 'PLKtqpr_EO-mnP8_STemsgQbHb2wJy2vjt', 11, current_timestamp, current_timestamp),
(17, 'Lí luận Văn học', 'PLg8dn1zkc1MvO398l1mwUXmm1nSK8GKGb', 11, current_timestamp, current_timestamp);

INSERT INTO centers (id, name, provinceId, address, description, image, createdAt, updatedAt) VALUES
(1, 'ALPHA Education - Học để dẫn đầu', 'PRO1', 'Đông Cao, Tráng Việt, Mê Linh', 'Trung tâm tiếng Anh với những giảng viên ưu tú', '', current_timestamp, current_timestamp),
(2, 'Alpha', 'PRO2', 'Trịnh Đình Trọng', 'Đáp ứng các nhu cầu về gia sư, học tập bổ sung kiến thức, ôn luyện cho các bạn', '', current_timestamp, current_timestamp),
(3, 'Mathnasium', 'PRO1', '1 Nguyên An Ninh, phường Dĩ An, thành phố Dĩ An, tỉnh Bình Dương', 'Trung tâm dạy toán với những giáo viên tốt nhất', '', current_timestamp, current_timestamp),
(4, 'Toán học cao cấp', 'PRO1', 'Cổ Nhuế, Phạm Văn Đồng', 'Trung tâm toán học cao cấp với những giảng viên tốt nhất', '', current_timestamp, current_timestamp),
(5, 'Đồng Tiến', 'PRO2', 'Đồng Tiến', 'Trung tâm Đồng Tiến là địa chỉ tin cậy của phụ huynh và học sinh', '', current_timestamp, current_timestamp),
(7, 'EDUSMART', 'PRO1', 'Khu C Tòa nhà T&T Riverview số 440 Vĩnh Hưng - P. Vĩnh Hưng - Q. Hoàng Mai', 'Hệ thống đào tạo luyện thi Toán xây dựng trên cơ sở mô hình trung tâm chuyên biệt luyện thi Toán tập trung vào việc xây dựng các lớp học thêm chất lượng cao ở Hà Nội cho các em học sinh cấp 2;3','', current_timestamp, current_timestamp),
(8, 'TITAN Education', 'PRO2', '91 Võ Thị Sáu, P. Võ Thị Sáu, Q3', 'Được thành lập năm 2010, với tập thể giáo viên giàu kinh nghiệm cùng chương trình đào tạo phù hợp, TITAN sẽ giúp học sinh cơ bản và dần dần tiếp cận với các kiến thức nâng cao, rèn khả năng tư duy, hình thành kỹ năng giải các bài tập, giúp các em đạt kết quả tốt ở trường cũng như các kỳ thi chuyển cấp và kỳ thi tuyển sinh đại học. Đối với những em có năng khiếu đặc biệt về toán, các giáo viên tại TITAN sẽ bồi dưỡng dạy chuyên sâu và nâng cao hơn, để các em có thể tự tin tham dự các kỳ thi Olympic, học sinh giỏi Quốc gia, Quốc tế.', '', current_timestamp, current_timestamp),
(9, 'BETA Education', 'PRO1', 'Biệt Thự 15 - HDi Homes, Số 201 Nguyễn Tuân, Thanh Xuân', 'Hệ thống giáo dục toán Beta Education - tiền thân là Trung tâm toán thầy Quốc Anh - được thành lập năm 2012 từ tình yêu với toán học và mong muốn đem cảm hứng học toán đến với các thế hệ học viên.', '', current_timestamp, current_timestamp),
(10, 'SKY Education', 'PRO1', 'Số nhà 29, ngõ 23 Đô Quang, Cầu Giấy', 'Được thành lập với đội ngũ giáo viên tâm huyết đến từ các trường THPT chuyên trong thành phố Hà Nội, Sky Education hướng đến môi trường giáo dục cải mạo, năng động dành cho học sinh từ lớp 4 đến lớp 12.', '', current_timestamp, current_timestamp);

