use education;

INSERT INTO Allcodes ("id", "keyMap", "type", "value", "createdAt", "updatedAt")  values
(1, 'R1', 'ROLE', 'Quản trị viên', current_timestamp, current_timestamp),
(2, 'R2', 'ROLE', 'Giáo viên', current_timestamp, current_timestamp),
(3, 'R3', 'ROLE', 'Học viên', current_timestamp, current_timestamp),
(4, 'S1', 'STATUS', 'Lịch hẹn mới', current_timestamp, current_timestamp),
(5, 'S2', 'STATUS', 'Đã xác nhận', current_timestamp, current_timestamp),
(6, 'S3', 'STATUS', 'Đã dạy xong', current_timestamp, current_timestamp),
(7, 'S4', 'STATUS', 'Đã hủy', current_timestamp, current_timestamp),
(8, 'T1', 'TIME', '8:00 - 9:00', current_timestamp, current_timestamp),
(9, 'T2', 'TIME', '9:00 - 10:00', current_timestamp, current_timestamp),
(10, 'T3', 'TIME', '10:00 - 11:00', current_timestamp, current_timestamp),
(11, 'T4', 'TIME', '11:00 - 12:00', current_timestamp, current_timestamp),
(12, 'T5', 'TIME', '13:00 - 14:00', current_timestamp, current_timestamp),
(13, 'T6', 'TIME', '14:00 - 15:00', current_timestamp, current_timestamp),
(14, 'T7', 'TIME', '15:00 - 16:00', current_timestamp, current_timestamp),
(15, 'T8', 'TIME', '16:00 - 17:00', current_timestamp, current_timestamp),
(16, 'P0', 'POSITION', 'Giáo viên', current_timestamp, current_timestamp),
(17, 'P1', 'POSITION', 'Thạc sĩ', current_timestamp, current_timestamp),
(18, 'P2', 'POSITION', 'Tiến sĩ', current_timestamp, current_timestamp),
(19, 'P3', 'POSITION', 'Phó giáo sư', current_timestamp, current_timestamp),
(20, 'P4', 'POSITION', 'Giáo sư', current_timestamp, current_timestamp),
(21, 'M', 'GENDER', 'Nam', current_timestamp, current_timestamp),
(22, 'F', 'GENDER', 'Nữ', current_timestamp, current_timestamp),
(23, 'O', 'GENDER', 'Khác', current_timestamp, current_timestamp),
(24, 'PRI1', 'PRICE', '200000', current_timestamp, current_timestamp),
(25, 'PRI2', 'PRICE', '250000', current_timestamp, current_timestamp),
(26, 'PRI3', 'PRICE', '300000', current_timestamp, current_timestamp),
(27, 'PRI4', 'PRICE', '350000', current_timestamp, current_timestamp),
(28, 'PRI5', 'PRICE', '400000', current_timestamp, current_timestamp),
(29, 'PRI6', 'PRICE', '450000', current_timestamp, current_timestamp),
(30, 'PRI7', 'PRICE', '500000', current_timestamp, current_timestamp),
(31, 'PAY1', 'PAYMENT', 'Tiền mặt', current_timestamp, current_timestamp),
(32, 'PAY2', 'PAYMENT', 'Thẻ ATM', current_timestamp, current_timestamp),
(33, 'PAY3', 'PAYMENT', 'Tất cả', current_timestamp, current_timestamp),
(34, 'PRO1', 'PROVINCE', 'Hà Nội', current_timestamp, current_timestamp),
(35, 'PRO2', 'PROVINCE', 'Hồ Chí Minh', current_timestamp, current_timestamp),
(36, 'PRO3', 'PROVINCE', 'Đà Nẵng', current_timestamp, current_timestamp),
(37, 'PRO4', 'PROVINCE', 'Cần Thơ', current_timestamp, current_timestamp),
(38, 'PRO5', 'PROVINCE', 'Bình Dương', current_timestamp, current_timestamp),
(39, 'PRO6', 'PROVINCE', 'Đồng Nai', current_timestamp, current_timestamp),
(40, 'PRO7', 'PROVINCE', 'Quảng Ninh', current_timestamp, current_timestamp),
(41, 'PRO8', 'PROVINCE', 'Thừa Thiên Huế', current_timestamp, current_timestamp),
(42, 'PRO9', 'PROVINCE', 'Quảng Bình', current_timestamp, current_timestamp),
(43, 'PRO10', 'PROVINCE', 'Khánh Hòa', current_timestamp, current_timestamp);
